apiRules:
- exclude:
  uidRegex: ^System\.
attributeRules:
- exclude:
  uidRegex: ^System
  type: Namespace
- exclude:
  uidRegex: ^System\.Object
  type: Type
- exclude:
  uidRegex: ^Object
  type: Type